version: '3'

services:

  redis:
    image: "redis:alpine"
    
  kafka:
    image: "spotify/kafka"
    environment:
      - ADVERTISED_HOST=kafka
      - ADVERTISED_PORT=9092
    ports:
      - "2181:2181"
      - "9092:9092"
      
  producer:
    build: 
      context: ./producer
      dockerfile: Dockerfile.producer
    environment:
      - PYTHONUNBUFFERED=0
        
  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile.consumer
    environment:
      - PYTHONUNBUFFERED=0
